### ISSUE TITLE
What's the preparations before using UART?

### ISSUE THREAD

**Issue by zhiyishou** [rpicopter/mw-service#1]
I installed this project, and the wired RX,TX,GND lines between Raspberry Pi 3+ and Arduino UNO(and MEGA2560 tested too), I get `UART: Failed to open UART device!` after run `./mw`, so I check device list and I don't see  the `/dev/ttyUSB0` but a `/dev/ttyAMA0`, and adding `-u /dev/ttyAMA0` as an argument will log `MW: Started`, then nothing will be updated.

Do this project need some preparations before performs on Pi or I missed sth.? Thx

**Comment by gregd72002** [comment]
hi, `MW: Started` means that the service is up and running ok. Now you can run a client to send some messages over the service, i.e:
`./mwtest` - this sends MSP_IDENT and MSP_STATUS to the your MultiWii and waits for the response
or `./mwcli` - to send arbitrary command from the command line

`mwtest` should return you `MultiWii connection seems to be working fine!`

**Comment by zhiyishou** [comment]
I'm clear now that this project is consist of service and client for cooperation, Thanks
